name: json_visual_editor
description: "JSON Visual Editor, alias JSON VE, is a visuel JSON editor made with flutter"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  menu_bar: ^0.5.3
  file_picker: ^11.0.3
  flutter_context_menu: ^0.4.2
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: CascadiaMono
      fonts:
      - asset: assets/cascadia-variable.ttf
      - asset: assets/cascadia-italic-variable.ttf
        style: italic